spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ccunsa_prd
    username: postgres
    password: 1234
    driverClassName: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: 'metrics'