spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ccunsa_tst
    username: root
    password: root123
    driverClassName: org.postgresql.Driver

management:
  endpoints:
    web:
      exposure:
        include: 'metrics'